### ISSUE TITLE
Found bug in the youtube channel link

### ISSUE THREAD

**Issue by bronzwikgk** [ortoniKC/LetXPath#1]
**Describe the bug**
https://youtub.com/letcode
this is the URL on the page. Seems it had an 'e' missing. 

When clicked on the above-mentioned link in the documentation, it takes the client to an error page. Probably, we can have a prior check for all the URLs in the documentation to check if they send to an unknown URL and show an alert[ "apology from the developer, he made a typing mistake, apology from the chrome developers, who couldn't fix it in 2020"]

**Expected behavior**
A clean, informative user experience

**Additional context**

**Comment by ortoniKC** [comment]
Hi, Thanks for bringing this. I Have fixed the issue.
