### ISSUE TITLE
[Violation] Permissions policy violation: unload is not allowed in this document," is typically related to browser security restrictions. The `document.execCommand('copy')`  having this issue while trying to add an copy to clipboard function

### ISSUE THREAD

**Issue by Pinky057** [ortoniKC/LetXPath#12]
The error encountering is, "[Violation] Permissions policy violation: unload is not allowed in this document," is typically related to browser security restrictions. The `document.execCommand('copy')` method, used for copying text to the clipboard, may trigger this violation in certain contexts, especially within browser extensions.

To address this issue, I have updated  `copyToClipboard` in my manifest.json

```javascript
function copyToClipboard(text) {
  navigator.clipboard.writeText(text)
    .then(() => {
      console.log('Text copied to clipboard:', text);
    })
    .catch((error) => {
      console.error('Unable to copy to clipboard:', error);
    });
}

function copySelectedToClipboard() {
  const selectedCheckboxes = document.querySelectorAll('input[type="checkbox"]:checked');
  let clipboardText = '';

  selectedCheckboxes.forEach((checkbox, index) => {
    const accordionContent = checkbox.nextElementSibling;
    const textarea = accordionContent.querySelector('textarea');
    const accordionText = textarea ? textarea.value.trim() : '';

    clipboardText += `${checkbox.value}\n${accordionText}`;

    // Add a newline separator between items, except for the last one
    if (index < selectedCheckboxes.length - 1) {
      clipboardText += '\n';
    }
  });

  copyToClipboard(clipboardText);
}
```

but still have the same error

**Comment by ortoniKC** [comment]
I am not facing any issues related to the clipboard.
Could you post a screenshot and also the browser name and version?

**Comment by Pinky057** [comment]
Thanks for the response, i was able to solve that issue.

**Comment by ghost** [comment]
content.7f229555.js:83 [Violation] Permissions policy violation: unload is not allowed in this document.
How can i resolve this issue
