### ISSUE TITLE
For google page i.e the url https://google.com - LetXPath fails to fetch the xpath for google searchbox or any random elements on that page

### ISSUE THREAD

**Issue by singhvk3004** [ortoniKC/LetXPath#2]
**Describe the bug**
https://google.com - > Unable to capture xpath for this page

**To Reproduce**
Steps to replicate the behavior:
1. Go to 'https://google.com'
2. Do right click on google search box and go to inspect element
3. LetXPath fails to fetch the xpaths.

No message is displayed. Please display the message if something went wrong or if it is inside the iframe.

**Expected behavior**
It should display a message if the google page or any page is inside the iframe.
For eg: This element might be inside iframe from different src.

**Screenshots**
![image](https://user-images.githubusercontent.com/65617246/90002379-3634b480-dcb0-11ea-8612-b4c87c87376c.png)

**Comment by ortoniRev** [comment]
Hi singhvk3004 , after installing kindly restart the browser. Navigate to google or any page and then open your devtools. 
I don't think there is an issues, please refer the attachment below. 
Thank you.

![image](https://user-images.githubusercontent.com/60606899/90011546-66d01a80-dcbf-11ea-9c62-05abcedd0114.png)

**Comment by ortoniKC** [comment]
Hi singhvk3004 , after installing kindly restart the browser. Navigate to google or any page and then open your devtools.
I don't think there is an issues, please refer the attachment below.
Please confirm and close the issue.
Thank you.

![image](https://user-images.githubusercontent.com/58769833/90011973-2a50ee80-dcc0-11ea-80c3-315ba64d8a36.png)

**Comment by singhvk3004** [comment]
Might be , please check once how it behave if any elements is inside the iframe tag and try to inspect the element. We might need to add message in such scenario..

**Comment by ortoniKC** [comment]
Yes, elements can be found within the iframe but as of now message is not shown. 
Thanks for the input, definitely I will do it **ASAP**.
Thanks for trying out **LetXPath**. Have  a great day, cheers 👍
