### ISSUE TITLE
Python snippets are obsolete

### ISSUE THREAD

**Issue by antaljani** [ortoniKC/LetXPath#4]
Wheh you are using Python snippets, it is using obsolete functions for click, getText, etc.
![image](https://user-images.githubusercontent.com/24701606/180406985-fd6c0511-0031-4829-adb1-51ce90ded4bf.png)

For example this case:
![image](https://user-images.githubusercontent.com/24701606/180408031-4ec21a95-a13a-42e0-8fd0-7ff1d5a09e36.png)

Clicking on the button highlighted with red arrow, it is generating the following code:
find_element_by_xpath("//div[@class='column']//img[1]").click();

Latest version of Selenium for Python using this code instead of previous:
find_element(By.XPATH,"//div[@class='column']//img[1]").click()

PLEASE NOTE: in Python language, semicolon at the end of line is also unnecessary! Please, remove it as well to keep the syntax correct.
Thank you in advnace.
Awaiting for update.

**Comment by ortoniKC** [comment]
Thanks for the update, I'll update the snippets.

**Comment by ortoniKC** [comment]
I have updated the extension, which should be live in the store within a week.
