### ISSUE TITLE
on german keyboard with mac user can not type @

### ISSUE THREAD

**Issue by manimovassagh** [ortoniKC/LetXPath#8]
**Describe the bug**
I am using German keyboard and when I want to type @ in Mac the plugin drop-down opened and does not let me to type anything.
I have to go to manage extensions and disable  the plugin, do the typing and again enable that.
see the attached photo
**To Reproduce**
first change key board layout in **mac** to german.
1. Go to any website for example google.com
2. try to type @something - the key is option L in mac
3. the dropdown opened and does not let you to continue.
4. See error on attached photo

**Expected behavior**
user can type @ with german keyboard on mac OS
<img width="1440" alt="Screenshot 2023-04-23 at 18 03 19" src="https://user-images.githubusercontent.com/74688476/233850839-8616d4e5-7657-4b92-bada-e2cd08c9eb5b.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome
 - Version latest

Update: The same issue is on English keyboard also.

**Comment by ortoniKC** [comment]
Hi, thanks for the report. I will give a quick fix.

**Comment by KamilDudekTR** [comment]
Hi,

When the fix will be ready? The extension is great, but this shortcut is really annoying :/
Cc: @ortoniKC

**Comment by ortoniKC** [comment]
I have updated the extension, which should be live in the store within a week.
