### ISSUE TITLE
Please fxe the bug of pySnippet, here is the code

### ISSUE THREAD

**Issue by justinlee-spo** [ortoniKC/LetXPath#9]
function pySnippet(type, codeType, codeValue, variable) {

    let str;
    // getAttribute Collection based XPath //input[@placeholder='first name & last name'] firstName" false
    switch (codeType) {
        case "CSS":
            str = `driver.find_element(by=By.CSS_SELECTOR, value="${codeValue}")`;
            break;
        case "Unique Class Atrribute":
            str = `driver.find_element(by=By.CLASS_NAME, value="${codeValue}")`;
            break;
        case "Unique TagName":
            str = `driver.find_element(by=By.TAG_NAME, value="${codeValue}")`;
            break;
        case "Link Text":
            str = `driver.find_element(by=By.LINK_TEXT, value="${codeValue}")`;
            break;
        case "Unique ID":
            str = `driver.find_element(by=By.ID, value="${codeValue}")`;
            break;
        case "Unique Name":
            str = `driver.find_element(by=By.NAME, value="${codeValue}")`;
            break;
        case "Unique PartialLinkText":
            str = `driver.find_element(by=By.PARTIAL_LINK_TEXT, value="${codeValue}")`;
            break;
        default:
            str = `driver.find_element(by=By.XPATH, value="${codeValue}")`;
            break;
    }
    switch (type) {
        case "click":
            str += `.click();`
            break;
        case "sendKeys":
            str += `.send_keys();`
            break;
        case "getAttribute":
            str += `.get_attribute();`
            break;
        case "getText":
            str += `.get_text();`
            break;
        default:
            str = 'hide';
            break;
    }
    return str;
}

**Comment by ortoniKC** [comment]
Thanks for the snippets, I have updated the extension, which should be live in the store within a week.
